{{- if eq .Values.secrets.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-secrets
  namespace: {{ include "namespace" . }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
type: Opaque
data:
{{ tpl (.Files.Glob "resources/secrets/*").AsSecrets . | indent 2 }}
{{- end -}}
