apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicename" . }}
  namespace: {{ include "namespace" . }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: {{ include "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $index, $port := .Values.ports }}
    - port: {{ $port.internalPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    app: {{ include "name" . }}
    release: {{ .Release.Name }}
