// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: apphcmanager.proto

package apphcmanager

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on GetApphcVersionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetApphcVersionRequest) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetApphcVersionRequestValidationError is the validation error returned by
// GetApphcVersionRequest.Validate if the designated constraints aren't met.
type GetApphcVersionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetApphcVersionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetApphcVersionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetApphcVersionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetApphcVersionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetApphcVersionRequestValidationError) ErrorName() string {
	return "GetApphcVersionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetApphcVersionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetApphcVersionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetApphcVersionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetApphcVersionRequestValidationError{}

// Validate checks the field values on GetApphcVersionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetApphcVersionResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Version

	// no validation rules for ApiVersion

	// no validation rules for GitCommit

	// no validation rules for GitState

	return nil
}

// GetApphcVersionResponseValidationError is the validation error returned by
// GetApphcVersionResponse.Validate if the designated constraints aren't met.
type GetApphcVersionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetApphcVersionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetApphcVersionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetApphcVersionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetApphcVersionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetApphcVersionResponseValidationError) ErrorName() string {
	return "GetApphcVersionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetApphcVersionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetApphcVersionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetApphcVersionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetApphcVersionResponseValidationError{}
