# Author  <dorzheho@cisco.com>
RANCHER_SERVER :=
APPHC_ADAPTERS_RANCHER_SERVER_ENDPOINT ?= https://$(RANCHER_SERVER):8443
APPHC_ADAPTERS_RANCHER_SERVER_CREDS_TOKEN :=
APPH_FLEX_API_HOST ?= $(RANCHER_SERVER)
APPH_FLEX_API_PORT ?= 7000
