# Author  <dorzheho@cisco.com>
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-secrets
  namespace: {{ include "namespace" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  EnvApphcBearerToken: {{ .Values.apphc.bearer_token | b64enc | quote }}
  EnvApphcAdaptersRancherServerCredsToken: {{ .Values.apphc.rancher_server_creds_token | b64enc | quote  }}
  EnvApphcAdaptersRancherCatalogPassword: {{  .Values.apphc.rancher_catalog_password | b64enc | quote }}
